### ISSUE TITLE
I'm Impressed. Can I help? Where is the source code? How did you do this?

### ISSUE THREAD

**Issue by MaxwellKendall** [reformed-standards/compendium#1]
Hey there.

I'm very impressed with the extent of data you've compiled. The website also is very nice.

Are you thinking about open-sourcing `reformedstandards.com`?

I'd love to help.

**Comment by honza** [comment]
I'm sorry for the late reply, somehow I missed the notification.

> I'm very impressed with the extent of data you've compiled. The website also is very nice.

Thanks!

> Are you thinking about open-sourcing reformedstandards.com?

No, not at the moment. 

> I'd love to help.

The biggest help in general is a) proofreading existing documents, and b) adding new documents.

**Comment by MaxwellKendall** [comment]
Got it; only interested in contributing as a developer! 

Thanks anyway! Great work.
