### ISSUE TITLE
Licensing on the WSC PCA

### ISSUE THREAD

**Issue by NonlinearFruit** [reformed-standards/compendium#22]
(I'm not a lawyer) 

Does the Apache License apply to the WSC PCA? I've been wanting to reach out and get permission from the PCA to use their revisions of the Westminster standards. Do you know someone I could reach out to?

**Comment by honza** [comment]
> (I'm not a lawyer)

Neither are we. I think the data is provided in hopes that it's useful for developers but if you need to use it for a commercial project, you should probably do your own due diligence in terms of tracking down the copyright holders.

Sorry :disappointed:
